# Generated by Django 5.1.2 on 2024-10-17 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_sticker_rename_is_sale_product_is_sale_customeralbum'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sticker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.sticker'),
        ),
    ]
