# Generated by Django 5.1.2 on 2024-10-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_sticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='image',
            field=models.ImageField(upload_to='uploads/stickers/'),
        ),
    ]
