# Generated by Django 5.1.2 on 2024-10-17 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_album_remove_product_category_remove_product_sticker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercollection',
            name='owned',
            field=models.BooleanField(default=False),
        ),
    ]
