# Generated by Django 5.1.2 on 2024-10-18 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_customercollection_owned'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectibleitem',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
    ]
